# DataSource Local (Dev)
spring.datasource.url=${DB_URL:${DB_LOCAL_URL:jdbc:postgresql://localhost:5432/facturacion_sunat}}
spring.datasource.username=${DB_USER:${DB_LOCAL_USER:postgres}}
spring.datasource.password=${DB_PASSWORD:${DB_LOCAL_PASSWORD:admin}}

# Logs SQL para desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Seeder (Solo activo en desarrollo)
app.seeder.enabled=true