# Server
server.port=8080

spring.application.name=facturacion-sunat

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/facturacion_sunat
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase - SOLO public/admin al arrancar
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-admin.xml
spring.liquibase.default-schema=public

