# DataSource Producción
spring.datasource.url=${DB_URL:${DB_PROD_URL}}
spring.datasource.username=${DB_USER:${DB_PROD_USER}}
spring.datasource.password=${DB_PASSWORD:${DB_PROD_PASSWORD}}

# Desactivar logs SQL detallados en producción por rendimiento y seguridad
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Seeder estrictamente desactivado en producción
app.seeder.enabled=false