# Server
server.port=${SERVER_PORT:8080}

# App
spring.application.name=facturacion-sunat
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.config.import=optional:file:.env[.properties]

# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-admin.xml
spring.liquibase.default-schema=public

# Multi-Tenancy
spring.jpa.properties.hibernate.multiTenancy=SCHEMA

# Storage por Tenant (Certificados, XML, CDR, PDF)
app.storage.base-path=${STORAGE_BASE_PATH:storage}

# SUNAT WebServices Endpoints (SOAP)
app.sunat.soap.beta-url=${SUNAT_SOAP_BETA_URL:https://e-beta.sunat.gob.pe/ol-ti-itcpfegem-beta/billService}
app.sunat.soap.prod-url=${SUNAT_SOAP_PROD_URL:https://e-factura.sunat.gob.pe/ol-ti-itcpfegem/billService}
app.sunat.soap.custom-url=${SUNAT_SOAP_CUSTOM_URL:}

